site_name: osintukraine docs
repo_url: https://github.com/conflict-investigations/docs.osintukraine.com
repo_name: conflict-investigations/docs.osintukraine.com
theme:
  name: material
  font: false
  logo: img/fellas.png
  # homepage: https://osintukraine.com
  favicon: img/fellas.png
  palette:
    primary: blue grey
